INSERT INTO cine_areas VALUES ('1', 'EDUCACION', '001');
INSERT INTO cine_areas VALUES ('2', 'HUMANIDADES Y ARTES', '001');
INSERT INTO cine_areas VALUES ('3', 'CIENCIAS SOCIALES, EDUCACION COMERCIAL Y DERECHO', '001');
INSERT INTO cine_areas VALUES ('4', 'CIENCIAS', '001');
INSERT INTO cine_areas VALUES ('5', 'INGENIERIA, INDUSTRIA Y CONSTRUCCION', '001');
INSERT INTO cine_areas VALUES ('6', 'AGRICULTURA', '001');
INSERT INTO cine_areas VALUES ('7', 'SALUD Y SERVICIOS SOCIALES', '001');
INSERT INTO cine_areas VALUES ('8', 'SERVICIOS', '001');
