INSERT INTO provincias VALUES ('1', 'Azuay');
INSERT INTO provincias VALUES ('2', 'Bolívar');
INSERT INTO provincias VALUES ('3', 'Cañar');
INSERT INTO provincias VALUES ('4', 'Carchi');
INSERT INTO provincias VALUES ('5', 'Cotopaxi');
INSERT INTO provincias VALUES ('6', 'Chimborazo');
INSERT INTO provincias VALUES ('7', 'El Oro');
INSERT INTO provincias VALUES ('8', 'Esmeraldas');
INSERT INTO provincias VALUES ('9', 'Guayas');
INSERT INTO provincias VALUES ('10', 'Imbabura');
INSERT INTO provincias VALUES ('11', 'Loja');
INSERT INTO provincias VALUES ('12', 'Los Ríos');
INSERT INTO provincias VALUES ('13', 'Manabí');
INSERT INTO provincias VALUES ('14', 'Morona Santiago');
INSERT INTO provincias VALUES ('15', 'Napo');
INSERT INTO provincias VALUES ('16', 'Pastaza');
INSERT INTO provincias VALUES ('17', 'Pichincha');
INSERT INTO provincias VALUES ('18', 'Tungurahua');
INSERT INTO provincias VALUES ('19', 'Zamora Chinchipe');
INSERT INTO provincias VALUES ('20', 'Galápagos');
INSERT INTO provincias VALUES ('21', 'Sucumbíos');
INSERT INTO provincias VALUES ('22', 'Orellana');
INSERT INTO provincias VALUES ('23', 'Santo Domingo de los Tsáchilas');
INSERT INTO provincias VALUES ('24', 'Santa Elena');
INSERT INTO provincias VALUES ('90', 'Zona no delimitada');
