INSERT INTO cantones VALUES ('1', '101', 'Cuenca');
INSERT INTO cantones VALUES ('1', '102', 'Girón');
INSERT INTO cantones VALUES ('1', '103', 'Gualaceo');
INSERT INTO cantones VALUES ('1', '104', 'Nabón');
INSERT INTO cantones VALUES ('1', '105', 'Paute');
INSERT INTO cantones VALUES ('1', '106', 'Pucará');
INSERT INTO cantones VALUES ('1', '107', 'San Fernando');
INSERT INTO cantones VALUES ('1', '108', 'Santa Isabel');
INSERT INTO cantones VALUES ('1', '109', 'Sigsig');
INSERT INTO cantones VALUES ('1', '110', 'Oña');
INSERT INTO cantones VALUES ('1', '111', 'Chordeleg');
INSERT INTO cantones VALUES ('1', '112', 'El Pan');
INSERT INTO cantones VALUES ('1', '113', 'Sevilla de Oro');
INSERT INTO cantones VALUES ('1', '114', 'Guachapala');
INSERT INTO cantones VALUES ('1', '115', 'Camilo Ponce Enríquez');
INSERT INTO cantones VALUES ('2', '201', 'Guaranda');
INSERT INTO cantones VALUES ('2', '202', 'Chillanes');
INSERT INTO cantones VALUES ('2', '203', 'Chimbo');
INSERT INTO cantones VALUES ('2', '204', 'Echeandia');
INSERT INTO cantones VALUES ('2', '205', 'San Miguel');
INSERT INTO cantones VALUES ('2', '206', 'Caluma');
INSERT INTO cantones VALUES ('2', '207', 'Las Naves');
INSERT INTO cantones VALUES ('3', '301', 'Azoques');
INSERT INTO cantones VALUES ('3', '302', 'Biblian');
INSERT INTO cantones VALUES ('3', '303', 'Cañar');
INSERT INTO cantones VALUES ('3', '304', 'La Troncal');
INSERT INTO cantones VALUES ('3', '305', 'El Tambo');
INSERT INTO cantones VALUES ('3', '306', 'Deleg');
INSERT INTO cantones VALUES ('3', '307', 'Suscal');
INSERT INTO cantones VALUES ('4', '401', 'Tulcán');
INSERT INTO cantones VALUES ('4', '402', 'Bolívar');
INSERT INTO cantones VALUES ('4', '403', 'Espejo');
INSERT INTO cantones VALUES ('4', '404', 'Mira');
INSERT INTO cantones VALUES ('4', '405', 'Montúfar');
INSERT INTO cantones VALUES ('4', '406', 'San Pedro de Huaca');
INSERT INTO cantones VALUES ('5', '501', 'Latacunga');
INSERT INTO cantones VALUES ('5', '502', 'La Maná');
INSERT INTO cantones VALUES ('5', '503', 'Pangua');
INSERT INTO cantones VALUES ('5', '504', 'Pujilí');
INSERT INTO cantones VALUES ('5', '505', 'Salcedo');
INSERT INTO cantones VALUES ('5', '506', 'Saquisilí');
INSERT INTO cantones VALUES ('5', '507', 'Sigchos');
INSERT INTO cantones VALUES ('6', '601', 'Riobamba');
INSERT INTO cantones VALUES ('6', '602', 'Alausí');
INSERT INTO cantones VALUES ('6', '603', 'Colta');
INSERT INTO cantones VALUES ('6', '604', 'Chambo');
INSERT INTO cantones VALUES ('6', '605', 'Chunchi');
INSERT INTO cantones VALUES ('6', '606', 'Guamote');
INSERT INTO cantones VALUES ('6', '607', 'Guano');
INSERT INTO cantones VALUES ('6', '608', 'Pallatanga');
INSERT INTO cantones VALUES ('6', '609', 'Penípe');
INSERT INTO cantones VALUES ('6', '610', 'Cumandá');
INSERT INTO cantones VALUES ('7', '701', 'Machala');
INSERT INTO cantones VALUES ('7', '702', 'Arenillas');
INSERT INTO cantones VALUES ('7', '703', 'Atahualpa');
INSERT INTO cantones VALUES ('7', '704', 'Balsas');
INSERT INTO cantones VALUES ('7', '705', 'Chilla');
INSERT INTO cantones VALUES ('7', '706', 'El Guabo');
INSERT INTO cantones VALUES ('7', '707', 'Huaquillas');
INSERT INTO cantones VALUES ('7', '708', 'Marcabelí');
INSERT INTO cantones VALUES ('7', '709', 'Pasaje');
INSERT INTO cantones VALUES ('7', '710', 'Piñas');
INSERT INTO cantones VALUES ('7', '711', 'Portovelo');
INSERT INTO cantones VALUES ('7', '712', 'Santa Rosa');
INSERT INTO cantones VALUES ('7', '713', 'Zaruma');
INSERT INTO cantones VALUES ('7', '714', 'Las Lajas');
INSERT INTO cantones VALUES ('8', '801', 'Esmeraldas');
INSERT INTO cantones VALUES ('8', '802', 'Eloy Alfaro');
INSERT INTO cantones VALUES ('8', '803', 'Muisne');
INSERT INTO cantones VALUES ('8', '804', 'Quininde');
INSERT INTO cantones VALUES ('8', '805', 'San Lorenzo');
INSERT INTO cantones VALUES ('8', '806', 'Atacames');
INSERT INTO cantones VALUES ('8', '807', 'RíoVerde');
INSERT INTO cantones VALUES ('8', '808', 'La Condordía');
INSERT INTO cantones VALUES ('9', '901', 'Guayaquil');
INSERT INTO cantones VALUES ('9', '902', 'Alfredo Baquerizo Moreno');
INSERT INTO cantones VALUES ('9', '903', 'Balao');
INSERT INTO cantones VALUES ('9', '904', 'Balzar');
INSERT INTO cantones VALUES ('9', '905', 'Colimes');
INSERT INTO cantones VALUES ('9', '906', 'Daule');
INSERT INTO cantones VALUES ('9', '907', 'Durán');
INSERT INTO cantones VALUES ('9', '908', 'Empalme');
INSERT INTO cantones VALUES ('9', '909', 'El Triunfo');
INSERT INTO cantones VALUES ('9', '910', 'Milagro');
INSERT INTO cantones VALUES ('9', '911', 'Naranjal');
INSERT INTO cantones VALUES ('9', '912', 'Naranjito');
INSERT INTO cantones VALUES ('9', '913', 'Palestina');
INSERT INTO cantones VALUES ('9', '914', 'Pedro Carbo');
INSERT INTO cantones VALUES ('9', '916', 'Samborondón');
INSERT INTO cantones VALUES ('9', '918', 'Santa Lucia');
INSERT INTO cantones VALUES ('9', '919', 'Salitre');
INSERT INTO cantones VALUES ('9', '920', 'San Jacinto de Yaguachi');
INSERT INTO cantones VALUES ('9', '921', 'Playas');
INSERT INTO cantones VALUES ('9', '922', 'Simón BolÍvar');
INSERT INTO cantones VALUES ('9', '923', 'Crnel. Marcelino Maridueña');
INSERT INTO cantones VALUES ('9', '924', 'Lomas de Sargentillo');
INSERT INTO cantones VALUES ('9', '925', 'Nobol');
INSERT INTO cantones VALUES ('9', '927', 'Gnral. Antonio Elizalde');
INSERT INTO cantones VALUES ('9', '928', 'Isidro Ayora');
INSERT INTO cantones VALUES ('10', '1001', 'Ibarra');
INSERT INTO cantones VALUES ('10', '1002', 'Antonio Ante');
INSERT INTO cantones VALUES ('10', '1003', 'Cotacahi');
INSERT INTO cantones VALUES ('10', '1004', 'Otavalo');
INSERT INTO cantones VALUES ('10', '1005', 'Pimampiro');
INSERT INTO cantones VALUES ('10', '1006', 'San Miguel de Urcuqui');
INSERT INTO cantones VALUES ('11', '1101', 'Loja');
INSERT INTO cantones VALUES ('11', '1102', 'Calvas');
INSERT INTO cantones VALUES ('11', '1103', 'Catamayo');
INSERT INTO cantones VALUES ('11', '1104', 'Célica');
INSERT INTO cantones VALUES ('11', '1105', 'Chaguarpamba');
INSERT INTO cantones VALUES ('11', '1106', 'Espíndola');
INSERT INTO cantones VALUES ('11', '1107', 'Gonzanamá');
INSERT INTO cantones VALUES ('11', '1108', 'Macará');
INSERT INTO cantones VALUES ('11', '1109', 'Paltas');
INSERT INTO cantones VALUES ('11', '1110', 'Puyango');
INSERT INTO cantones VALUES ('11', '1111', 'Saraguro');
INSERT INTO cantones VALUES ('11', '1112', 'Sozoranga');
INSERT INTO cantones VALUES ('11', '1113', 'Zapotillo');
INSERT INTO cantones VALUES ('11', '1114', 'Pindal');
INSERT INTO cantones VALUES ('11', '1115', 'Quilanga');
INSERT INTO cantones VALUES ('11', '1116', 'Olemdo');
INSERT INTO cantones VALUES ('12', '1201', 'Babahoyo');
INSERT INTO cantones VALUES ('12', '1202', 'Baba');
INSERT INTO cantones VALUES ('12', '1203', 'Montalvo');
INSERT INTO cantones VALUES ('12', '1204', 'Puebloviejo');
INSERT INTO cantones VALUES ('12', '1205', 'Quevedo');
INSERT INTO cantones VALUES ('12', '1206', 'Urdaneta');
INSERT INTO cantones VALUES ('12', '1207', 'Ventanas');
INSERT INTO cantones VALUES ('12', '1208', 'Vinces');
INSERT INTO cantones VALUES ('12', '1209', 'Palenque');
INSERT INTO cantones VALUES ('12', '1210', 'Buena Fé');
INSERT INTO cantones VALUES ('12', '1211', 'Valencia');
INSERT INTO cantones VALUES ('12', '1212', 'Mocache');
INSERT INTO cantones VALUES ('12', '1213', 'Quinsaloma');
INSERT INTO cantones VALUES ('13', '1301', 'Portoviejo');
INSERT INTO cantones VALUES ('13', '1302', 'Bolívar');
INSERT INTO cantones VALUES ('13', '1303', 'Chone');
INSERT INTO cantones VALUES ('13', '1304', 'El Carmen');
INSERT INTO cantones VALUES ('13', '1305', 'Flavio Alfaro');
INSERT INTO cantones VALUES ('13', '1306', 'Jipijapa');
INSERT INTO cantones VALUES ('13', '1307', 'Junín');
INSERT INTO cantones VALUES ('13', '1308', 'Manta');
INSERT INTO cantones VALUES ('13', '1309', 'Montecristi');
INSERT INTO cantones VALUES ('13', '1310', 'Paján');
INSERT INTO cantones VALUES ('13', '1311', 'Pichincha');
INSERT INTO cantones VALUES ('13', '1312', 'Rocafuerte');
INSERT INTO cantones VALUES ('13', '1313', 'Santa Ana');
INSERT INTO cantones VALUES ('13', '1314', 'Sucre');
INSERT INTO cantones VALUES ('13', '1315', 'Tosagua');
INSERT INTO cantones VALUES ('13', '1316', '24 de Mayo');
INSERT INTO cantones VALUES ('13', '1317', 'Pedernales');
INSERT INTO cantones VALUES ('13', '1318', 'Olmedo');
INSERT INTO cantones VALUES ('13', '1319', 'Puerto López');
INSERT INTO cantones VALUES ('13', '1320', 'Jama');
INSERT INTO cantones VALUES ('13', '1321', 'Jaramijó');
INSERT INTO cantones VALUES ('13', '1322', 'San Vicente');
INSERT INTO cantones VALUES ('14', '1401', 'Morona');
INSERT INTO cantones VALUES ('14', '1402', 'Gualaquiza');
INSERT INTO cantones VALUES ('14', '1403', 'Limón Indanza');
INSERT INTO cantones VALUES ('14', '1404', 'Palora');
INSERT INTO cantones VALUES ('14', '1405', 'Santiago');
INSERT INTO cantones VALUES ('14', '1406', 'Sucúa');
INSERT INTO cantones VALUES ('14', '1407', 'Huamboya');
INSERT INTO cantones VALUES ('14', '1408', 'San Juan Bosco');
INSERT INTO cantones VALUES ('14', '1409', 'Taisha');
INSERT INTO cantones VALUES ('14', '1410', 'Logroño');
INSERT INTO cantones VALUES ('14', '1411', 'Pablo Sexto');
INSERT INTO cantones VALUES ('14', '1412', 'Tiwintza');
INSERT INTO cantones VALUES ('15', '1501', 'Tena');
INSERT INTO cantones VALUES ('15', '1503', 'Archidona');
INSERT INTO cantones VALUES ('15', '1504', 'El Chaco');
INSERT INTO cantones VALUES ('15', '1507', 'Quijos');
INSERT INTO cantones VALUES ('15', '1509', 'Carlos Julio Arrosemena Tola');
INSERT INTO cantones VALUES ('16', '1601', 'Pastaza');
INSERT INTO cantones VALUES ('16', '1602', 'Mera');
INSERT INTO cantones VALUES ('16', '1603', 'Santa Clara');
INSERT INTO cantones VALUES ('16', '1604', 'Arajuno');
INSERT INTO cantones VALUES ('17', '1701', 'Quito');
INSERT INTO cantones VALUES ('17', '1702', 'Cayambe');
INSERT INTO cantones VALUES ('17', '1703', 'Mejía');
INSERT INTO cantones VALUES ('17', '1704', 'Pedro Moncayo');
INSERT INTO cantones VALUES ('17', '1705', 'Rumiñahui');
INSERT INTO cantones VALUES ('17', '1707', 'San Miguel de los Bancos');
INSERT INTO cantones VALUES ('17', '1708', 'Pedro Vicente Maldonado');
INSERT INTO cantones VALUES ('17', '1709', 'Puerto Quito');
INSERT INTO cantones VALUES ('18', '1801', 'Ambato');
INSERT INTO cantones VALUES ('18', '1802', 'Baños de Agua Santa');
INSERT INTO cantones VALUES ('18', '1803', 'Cevallos');
INSERT INTO cantones VALUES ('18', '1804', 'Mocha');
INSERT INTO cantones VALUES ('18', '1805', 'Patate');
INSERT INTO cantones VALUES ('18', '1806', 'Quero');
INSERT INTO cantones VALUES ('18', '1807', 'San Pedro de Pelileo');
INSERT INTO cantones VALUES ('18', '1808', 'Santiago de Pillaro');
INSERT INTO cantones VALUES ('18', '1809', 'Tisaleo');
INSERT INTO cantones VALUES ('19', '1901', 'Zamora');
INSERT INTO cantones VALUES ('19', '1902', 'Chinchipe');
INSERT INTO cantones VALUES ('19', '1903', 'Nangaritza');
INSERT INTO cantones VALUES ('19', '1904', 'Yacuambi');
INSERT INTO cantones VALUES ('19', '1905', 'Yantzaza');
INSERT INTO cantones VALUES ('19', '1906', 'El Pangui');
INSERT INTO cantones VALUES ('19', '1907', 'Centinela del Cóndor');
INSERT INTO cantones VALUES ('19', '1908', 'Palanda');
INSERT INTO cantones VALUES ('19', '1909', 'Paquisha');
INSERT INTO cantones VALUES ('20', '2001', 'San Cristobal');
INSERT INTO cantones VALUES ('20', '2002', 'Isabela');
INSERT INTO cantones VALUES ('20', '2003', 'Santa Cruz');
INSERT INTO cantones VALUES ('21', '2101', 'Lago Agrio');
INSERT INTO cantones VALUES ('21', '2102', 'Gonzalo Pizarro');
INSERT INTO cantones VALUES ('21', '2103', 'Putumayo');
INSERT INTO cantones VALUES ('21', '2104', 'Shushufindi');
INSERT INTO cantones VALUES ('21', '2105', 'Sucumbios');
INSERT INTO cantones VALUES ('21', '2106', 'Cascales');
INSERT INTO cantones VALUES ('21', '2107', 'Cuyabeno');
INSERT INTO cantones VALUES ('22', '2201', 'Orellana');
INSERT INTO cantones VALUES ('22', '2202', 'Aguarico');
INSERT INTO cantones VALUES ('22', '2203', 'La Joya de Los Sachas');
INSERT INTO cantones VALUES ('22', '2204', 'Loreto');
INSERT INTO cantones VALUES ('23', '2301', 'Santo Domingo');
INSERT INTO cantones VALUES ('24', '2401', 'Santa Elena');
INSERT INTO cantones VALUES ('24', '2402', 'La Libertad');
INSERT INTO cantones VALUES ('24', '2403', 'Salinas');
INSERT INTO cantones VALUES ('90', '9001', 'Las Golondrinas');
INSERT INTO cantones VALUES ('90', '9003', 'Manga del Cura');
INSERT INTO cantones VALUES ('90', '9004', 'El Piedrero');
