INSERT INTO tipos_de_visa VALUES ('1', 'Visa 12 - NO INMIGRANTE');
INSERT INTO tipos_de_visa VALUES ('2', 'Visa 9 - INMIGRANTE');
INSERT INTO tipos_de_visa VALUES ('4', 'SOLICITANTE DE REFUGIO');
INSERT INTO tipos_de_visa VALUES ('3', 'VISA DE REFUGIO O CARNET DE SOLICITANTE DE REFUGIO');
